### ISSUE TITLE
CLI does not correctly validate sink properties file

### ISSUE THREAD

**Issue by IDispose** [Landoop/kafka-connect-tools#30]
My sink properties file had an error. Instead of 

`connect.kudu.master`

I had 

`connect.kudu.kaster`

cli created a new connector and said properties was valid. However, confluent connect log logged a bunch of errors and exceptions which went away after correcting the property.

**Comment by andrewstevenson** [comment]
@IDispose The connector has defaults for `connect.kudu.master` so it will try localhost, unfortunately the Connect framework will happily ignore your misconfiguration.
